Foro.Mvc/Models/Topics/TopicAddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Foro.Mvc.Models.Topics
{
    public class TopicAddViewModel
    {
        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        public string UserName { get; set; }
    }
}

Foro.Mvc/Models/Topics/TopicDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Foro.Mvc.Models.Topics
{
    public class TopicDetailViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string UserName { get; set; }
        public string CreationDateTimeString { get; set; }

        public IEnumerable<EntryDetailViewModel> Entries { get; set; }
    }

    public class EntryDetailViewModel 
    {
        public int Id { get; set; }
        public string Comment { get; set; }
        public string UserName { get; set; }
        public string CreationDateTimeString { get; set; }
    }
}

Foro.Mvc/Models/Topics/TopicShortViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Foro.Mvc.Models.Topics
{
    public class TopicShortViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string UserName { get; set; }
        public DateTime CreationDateTime { get; set; }
        public string CreationDateTimeString { get; set; }
    }
}

Foro.Mvc/Controllers/TopicController.cs
using Foro.Dto.Topic;
using Foro.Dto.Entry;
using Foro.Mvc.Models.Topics;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Foro.Mvc.Helpers;
using Foro.Dto.User;

namespace Foro.Mvc.Controllers
{
    public class TopicController : Controller
    {
        private HttpClient client;
        private const string apiURL = "http://localhost:30882/";
        private UserApiHelper userApiHelper = new UserApiHelper();

        public TopicController()
        { }

        private async Task<DTOUserResponse> GetUserDTO() 
        {
            string userId = User.Identity.GetUserId();
            Guid userGuid = new Guid(userId);
            return await userApiHelper.GetUserDTOByUserGuidAsync(userGuid);
        }

        private HttpClient GetHttpClient()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri(apiURL);
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            return client;
        }

        async Task<List<DTOAddTopicResponse>> GetTopicsDTOAsync()
        {
            List<DTOAddTopicResponse> listTopicDTO = new List<DTOAddTopicResponse>();

            using (var client = GetHttpClient())
            {
                HttpResponseMessage response = await client.GetAsync("api/topic");
                if (response.IsSuccessStatusCode)
                {
                    string topicsJson = await response.Content.ReadAsStringAsync();

                    var topicsDTODeserialzed = JsonConvert.DeserializeObject<List<DTOAddTopicResponse>>(topicsJson);
                    if (topicsDTODeserialzed.Count() > 0)
                    {
                        listTopicDTO.AddRange(topicsDTODeserialzed);
                    }
                }
            }

            return listTopicDTO;
        }

        async Task<DTOAddTopicResponse> GetTopicDTOAsync(int id)
        {
            DTOAddTopicResponse topicDto = new DTOAddTopicResponse();

            using (var client = GetHttpClient())
            {
                HttpResponseMessage response = await client.GetAsync(string.Format("api/topic/{0}", id.ToString()));
                if (response.IsSuccessStatusCode)
                {
                    topicDto = await response.Content.ReadAsAsync<DTOAddTopicResponse>();                   
                }
            }

            return topicDto;
        }

        async Task<List<DTOEntryResponse>> GetEntriesDTOAsync(int topicId)
        {
            List<DTOEntryResponse> listEntryDTO = new List<DTOEntryResponse>();

            using (var client = GetHttpClient())
            {
                HttpResponseMessage response = await client.GetAsync(string.Format("api/entry/{0}", topicId.ToString()));
                if (response.IsSuccessStatusCode)
                {
                    string entriesJson = await response.Content.ReadAsStringAsync();

                    var entriesDTODeserialzed = JsonConvert.DeserializeObject<List<DTOEntryResponse>>(entriesJson);
                    if (entriesDTODeserialzed.Count() > 0)
                    {
                        listEntryDTO.AddRange(entriesDTODeserialzed);
                    }
                }
            }

            return listEntryDTO;
        }

        private void SubscribeUserToNotifications() 
        { }

        public async Task<ActionResult> Index()
        {
            var result = await GetTopicsDTOAsync();

            var model = result.ConvertAll(t => new TopicShortViewModel() { 
                                                Id = t.Id,
                                                Title = t.Title,
                                                ShortDescription = string.Format("{0} ... ", t.Description.Substring(0, t.Description.Length > 500 ? 500 : t.Description.Length)),
                                                UserName = t.UserName,
                                                CreationDateTime = t.CreationDateTime.GetValueOrDefault(),
                                                CreationDateTimeString = t.CreationDateTime.GetValueOrDefault().ToString("dd MMM yyyy")
                                            });

            return View(model);
        }

        public async Task<ActionResult> Detail(int id) 
        {
            var result = await GetTopicDTOAsync(id);
            var resultEntries = await GetEntriesDTOAsync(id);

            var model = new TopicDetailViewModel()
            {
                Id = result.Id,
                Title = result.Title,
                Description = result.Description,
                UserName = result.UserName,
                CreationDateTimeString = result.CreationDateTime.GetValueOrDefault().ToString("dd MMM yyyy"),
                Entries = resultEntries.ConvertAll(r => new EntryDetailViewModel() { Id = r.Id, Comment = r.Comment, UserName = r.UserName, CreationDateTimeString = r.CreationDateTime.GetValueOrDefault().ToString("dd MMM yyyy") })
            };

            return View(model);
        }

        public ActionResult Create()
        {
            TopicAddViewModel model = new TopicAddViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Create(TopicAddViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var userDTO = await GetUserDTO();

                    using (var client = GetHttpClient())
                    {
                        var topicDTO = new DTOAddTopicRequest() { Title = model.Title, Description = model.Description, UserName = userDTO.UserName };
                        var response = await client.PostAsJsonAsync("api/topic", topicDTO);
                        if (response.IsSuccessStatusCode)
                        {
                            // Get the URI of the created resource.
                            //Uri gizmoUrl = response.Headers.Location;

                            return RedirectToAction("Index");
                        }
                    }
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<ActionResult> AddEntry(int TopicId, string EntryComent) 
        {
            if(TopicId > 0 && !string.IsNullOrEmpty(EntryComent))
            {
                var userDTO = await GetUserDTO();

                using (var client = GetHttpClient())
                {
                    var entryDTO = new DTOEntryRequest() { TopicId = TopicId, Comment = EntryComent, UserName = userDTO.UserName };
                    var response = await client.PostAsJsonAsync("api/entry", entryDTO);
                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Detail", new { id = TopicId });
                    }
                }
            }

            return RedirectToAction("Detail", new { id = TopicId });
        }

    }
}

Foro.Mvc/Views/Topic/Create.cshtml
@model Foro.Mvc.Models.Topics.TopicAddViewModel

@{
    ViewBag.Title = "Create";
}

<h2>New Topic</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div>
        <div>
            @Html.LabelFor(model => model.Title)
        </div>
        <div>
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { style = "width: 100%;" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
        <div>
            @Html.LabelFor(model => model.Description)
        </div>
        <div>
            @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { style = "width: 100%;" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
        <div>
            <br />
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
}

<div>
    <br />
    @Html.ActionLink("<< Back to Topics", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Foro.Mvc/Views/Topic/Detail.cshtml
@model Foro.Mvc.Models.Topics.TopicDetailViewModel

@{
    ViewBag.Title = "Detail";
}

<div style="margin: 30px 0 0 0">
    <div style="font-size:26px; color:#2A7CC0">
        @Html.DisplayFor(model => model.Title)
    </div>
    <div style="margin: 0 0 15px 0;">
        <b>User:</b> @Html.DisplayFor(model => model.UserName) |
        <b>Date:</b> @Html.DisplayFor(model => model.CreationDateTimeString)
    </div>
    <div>
        @Html.DisplayFor(model => model.Description)
    </div>
</div>
@foreach (var item in Model.Entries) 
{
    <hr />
    <div>
        <div style="margin: 0 0 5px 0;">
            <b>User:</b> @item.UserName |
            <b>Date:</b> @item.CreationDateTimeString
        </div>
        <div>@item.Comment</div>
    </div> 
}

@using (Html.BeginForm("AddEntry", "Topic", FormMethod.Post))
{
    <br />
    if (Request.IsAuthenticated)
    {
        <br />
        <div>
            <b>Add Entry</b>
            <br />
            @Html.Hidden("TopicId", Model.Id)
            @Html.TextArea("EntryComent", new { style = "width: 100%" })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            <br /><br />
            <input type="submit" value="Add Entry" class="btn btn-default" />
        </div>
    }
}


<br />
<p>
    @Html.ActionLink("<< Back to Topics", "Index")
</p>

Foro.Mvc/Views/Topic/Index.cshtml
@model IEnumerable<Foro.Mvc.Models.Topics.TopicShortViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Topic List</h2>

@if (Request.IsAuthenticated)
{
    @Html.ActionLink("Add New Topic", "Create", null, new { @style = "margin: 0 0 0 5px;" })
    <br /><br />
}

<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <div style="font-size:large; margin: 0 0 8px 0;">
                    @Html.ActionLink(item.Title, "Detail", "Topic", new { id = item.Id }, null)
                </div>
                <div style="margin: 0 0 8px 0;">
                    @Html.DisplayFor(modelItem => item.ShortDescription)
                </div>
                <div style="margin: 0 0 7px 0;">
                    <b>User:</b> @Html.DisplayFor(modelItem => item.UserName) | 
                    <b>Date:</b> @Html.DisplayFor(modelItem => item.CreationDateTimeString)
                </div>
            </td>
        </tr>
    }
</table>

@if (Request.IsAuthenticated)
{
    @Html.ActionLink("Add New Topic", "Create", null, new { @style = "margin: 0 0 0 5px;" })
    <br /><br />
}